### ISSUE TITLE
[Frontend] - Navbar

### ISSUE THREAD

**Issue by Kartik-Aggarwal5** [allenli75/clubwebsite#327]
**Figma Link:** https://www.figma.com/file/ILRciTrTtncSzE8ZqC1dzo/Sproul.club?node-id=1-3868&t=z4uEsQQWiA1SNe8L-0
File name is: **High-Fi +Figma Prototype**

The structure for this project is a bit different (better) than previous projects you might have worked on.
You can find the Navbar folder in _components -> layout -> Navbar_

**Points to Remember:** 

- Please create a separate branch off of **_develop_** but don't overdo it. (fewer branches make life easy)
- Coordinate with your pair programmer (if you have one) to avoid conflicts. (I would suggest pair-programming instead of dividing segments)

**Comment by ggams2020** [comment]
@Kartik-Aggarwal5 I need access to the figma
